# -*- coding: utf-8 -*-
"""Satisfaction Level.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAVkq4LTQaSVC6U5IK92CqkTG6qO2Ywa
"""

#Import modul
import numpy as np
import pandas as pd
import statsmodels
import patsy
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

#import model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

import warnings
warnings.filterwarnings("ignore")



#baca data
df = pd.read_csv('customer_behaviour.csv')
df.head()

df.info()

df.columns

df['City'].unique()

df['Membership Type'].unique()

df['Average Rating'].unique()

df['Discount Applied'].unique()

df['Satisfaction Level'].unique()

df.duplicated().sum()

df['Customer ID'].duplicated().sum()

df.isna().sum()

#Mengisi nilai kosong pada Satisfaction Level dengan Modus
modus_value = df['Satisfaction Level'].mode()[0]  # Mengambil nilai modus
df['Satisfaction Level'].fillna(modus_value, inplace=True)  # Mengisi nilai kosong dengan modus

df.isna().sum()

df['Spend per Item'] = df['Total Spend'] / df['Items Purchased']
# Untuk lebih mengetahui lebih baik
# hubungan antara variabel independen dan kepuasan pelanggan,
#coba hitung Spend per Item dan menambahkannya sebagai kolom baru di dataframe

df.head()

#Download file bersihnya (non encoding) untuk Looker
from google.colab import files
df.to_csv('cleaned_customerbehaviour.csv', index=False)
files.download('cleaned_customerbehaviour.csv')

# Initialize LabelEncoders
le_gender = LabelEncoder()
le_membership = LabelEncoder()
le_discount = LabelEncoder()
le_satisfaction = LabelEncoder()

# Encode the columns
df['Gender'] = le_gender.fit_transform(df['Gender'])
df['Membership Type'] = le_membership.fit_transform(df['Membership Type'])
df['Discount Applied'] = le_discount.fit_transform(df['Discount Applied'])
df['Satisfaction Level'] = le_satisfaction.fit_transform(df['Satisfaction Level'])

df.head()

df.info()

#Download file bersihnya (encoding)
from google.colab import files
df.to_csv('cleanedencode_customerbehaviour.csv', index=False)
files.download('cleanedencode_customerbehaviour.csv')

"""# Uji Normalitas, Detect Outlier, Delete Ooutlier"""

import matplotlib.pyplot as plt

# Misal data kamu ada di dataframe df
features = ['Age', 'Total Spend', 'Items Purchased', 'Average Rating', 'Discount Applied', 'Days Since Last Purchase']

for feature in features:
    plt.figure(figsize=(8, 6))
    plt.scatter(df[feature], df['Satisfaction Level'])
    plt.title(f'{feature} vs Satisfaction Level')
    plt.xlabel(feature)
    plt.ylabel('Satisfaction Level')
    plt.show()

#Distribusi data tidak normal, maka akan menggunakan model Logistic Regression, Decision Tree, atau Random Forest.
#tetap hapus dulu outliernya

#Age
sns.boxplot(df['Age'])
#bagus, tidak ada outlier

sns.boxplot(df['Total Spend'])
#bagus juga

sns.boxplot(df['Items Purchased'])
#bagus

sns.boxplot(df['Average Rating'])
#bagus

sns.boxplot(df['Discount Applied'])

sns.boxplot(df['Days Since Last Purchase'])

"""# Berhubung data tidak berdistribusi normal, kita coba pakai model Random Forest"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

df.info()

#input fitur
X = df[['Age', 'Items Purchased', 'Spend per Item', 'Average Rating', 'Discount Applied', 'Days Since Last Purchase']]
y = df['Satisfaction Level']

# Training dan testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

# Membuat model Random Forest Regressor
model = RandomForestRegressor(random_state=42, n_estimators=100)

# Melatih model
model.fit(X_train, y_train)

# Prediksi pada data testing
y_pred = model.predict(X_test)

# Evaluasi model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

X_test #ini buat apaan ya? wkwk

# Assuming 'model' is your trained RandomForestRegressor
#Age, Items (counts), Spend per Item, Average Rating, Discount Applied Yes = 1/ No = 0, Days Since Last Purchase)
example = [[35, 4, 11200, 4, 0, 15]]
satisfaction_level = model.predict(example)

# Convert the predicted value to an integer between 0 and 2
predicted_class = int(round(satisfaction_level[0]))

# Ensure the predicted class is within the valid range
predicted_class = max(0, min(predicted_class, 2))

# Map the predicted class to the corresponding label
satisfaction_labels = ["Unsatisfied", "Neutral", "Satisfied"]
predicted_label = satisfaction_labels[predicted_class]

print(f'Predicted Satisfaction Level: {predicted_label}')